#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum unicode_names { SMILE, FROWN, POOP, THUMBSUP, THUMBSDOWN, BANG };

const uint32_t PROGMEM unicode_map[] = {[SMILE] = 0x1F603, [FROWN] = 0x1F626, [POOP] = 0x1F4A9, [THUMBSUP] = 0x1F44D, [THUMBSDOWN] = 0x1F44E, [BANG] = 0x203D};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_BSPC, KC_A, LGUI_T(KC_R), LALT_T(KC_S), KC_T, KC_D, KC_H, KC_N, RALT_T(KC_E), RGUI_T(KC_I), KC_O, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, OSM(MOD_LSFT), KC_SPC, OSL(1), OSM(MOD_RCTL)),

                                                              [1] = LAYOUT(KC_ESC, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_SCLN, KC_COLN, KC_TAB, KC_UNDS, KC_QUOT, KC_DQUO, KC_SLSH, KC_LEFT_BRACKET, KC_LCBR, KC_RCBR, KC_RIGHT_BRACKET, KC_ENT, KC_TILD, KC_GRV, KC_EQL, KC_PIPE, KC_BSLS, OSL(4), KC_LPRN, KC_RPRN, KC_TRNS, TO(3), KC_EXLM, KC_MINS, TO(2), KC_TRNS),

                                                              [2] = LAYOUT(KC_ESC, KC_NO, KC_NO, KC_NO, KC_PSLS, KC_PMNS, KC_7, KC_8, KC_9, KC_BSPC, KC_BSPC, KC_LGUI, KC_LALT, KC_NO, KC_PAST, KC_PPLS, KC_4, KC_5, KC_6, KC_ENT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NLCK, KC_0, KC_1, KC_2, KC_3, KC_DOT, TO(0), KC_SPC, KC_NO, KC_RCTL),

                                                              [3] = LAYOUT(KC_ESC, KC_NO, KC_MS_U, KC_NO, KC_WH_U, KC_PGUP, KC_HOME, KC_END, KC_NO, KC_NO, KC_TAB, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_ACL0, KC_ACL1, KC_ACL2, KC_BTN2, KC_PGDOWN, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_BTN1, KC_NO, KC_RCTL),

                                                              [4] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_RALT, KC_LGUI, KC_LALT, KC_NO, KC_NO, KC_F11, X(SMILE), X(FROWN), X(POOP), X(BANG), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F12, X(THUMBSUP), X(THUMBSDOWN), KC_NO, KC_NO, TO(0), KC_LSFT, KC_NO, KC_RCTL)};

uint16_t mod_state;
bool     process_record_user(uint16_t keycode, keyrecord_t *record) {
    mod_state = get_mods();
    switch (keycode) {
        case KC_BSPC: {
            static bool delkey_registered;
            if (record->event.pressed) {
                if (mod_state & MOD_MASK_SHIFT) {
                    del_mods(MOD_MASK_SHIFT);
                    register_code(KC_DEL);
                    delkey_registered = true;
                    set_mods(mod_state);
                    return false;
                }
            } else {
                if (delkey_registered) {
                    unregister_code(KC_DEL);
                    delkey_registered = false;
                    return false;
                }
            }
        }
            return true;
    }
    return true;
}
